create or replace PROCEDURE     UPDATE_CUSTOMER
    (IN CUSTOMER_ID NUMBER)
    MODIFIES SQL DATA
BEGIN ATOMIC

    DECLARE count_me INTEGER;
    SET count_me = 0;
    --DECLARE now TIMESTAMP;
    --SELECT CURRENT_TIMESTAMP INTO now FROM DUAL;
    -- Update the current status.
    UPDATE CUSTOMER SET TS_UPDATE = CURRENT_TIMESTAMP
    WHERE ID = CUSTOMER_ID;
END;

