DROP TABLE CUSTOMER_ADDRESS IF EXISTS;
DROP TABLE ADDRESS IF EXISTS;
DROP TABLE CUSTOMER IF EXISTS;
DROP TABLE DEVICE IF EXISTS;

CREATE TABLE CUSTOMER (
	ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	LA_NAME VARCHAR2(100 CHAR) NOT NULL,
    LA_TRIGGER_COUNTER VARCHAR2(100 CHAR) NULL,
    TS_UPDATE TIMESTAMP NULL,
    CONSTRAINT ID_CK CHECK (ID < 1000)
)
;

CREATE TABLE ADDRESS (
	ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	NU_NUMBER NUMBER NOT NULL,
    LA_STREET VARCHAR2(100 CHAR) NULL,
    LA_POSTAL_CODE VARCHAR2(10 CHAR) NULL,
    LA_CITY VARCHAR2(100 CHAR) NULL,
    LA_COUNTRY VARCHAR2(100 CHAR) NULL,
    TS_UPDATE TIMESTAMP NULL
)
;

CREATE TABLE CUSTOMER_ADDRESS (
	ID_CUSTOMER NUMBER(19,0) NOT NULL,
	ID_ADDRESS NUMBER(19,0) NOT NULL,
    CONSTRAINT FK_ID_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID),
    CONSTRAINT FK_ID_ADDRESS FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS (ID) ON DELETE CASCADE
)
;

CREATE TABLE DEVICE (
	ID NUMBER(19,0),
	LA_NAME VARCHAR2(30 CHAR),
    LA_DESCRIPTION VARCHAR2(100 CHAR) UNIQUE,
    TS_UPDATE TIMESTAMP UNIQUE,
    CONSTRAINT PK_DEVICE PRIMARY KEY (ID, LA_NAME)
)
;
